name: uydu_kumanda
description: media tivi - Linux uydu/IPTV alıcısı uzaktan kumanda uygulaması.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  shared_preferences: ^2.2.0
  webview_flutter: ^4.4.0
  speech_to_text: ^6.6.0
  share_plus: ^7.2.2
  path_provider: ^2.1.2

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
